// Code generated by mockery v2.32.4. DO NOT EDIT.

package catalog

import (
	context "context"

	proxysnapshot "github.com/hashicorp/consul/internal/mesh/proxy-snapshot"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionLimiter is an autogenerated mock type for the SessionLimiter type
type MockSessionLimiter struct {
	mock.Mock
}

// BeginSession provides a mock function with given fields:
func (_m *MockSessionLimiter) BeginSession() (proxysnapshot.Session, error) {
	ret := _m.Called()

	var r0 proxysnapshot.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() (proxysnapshot.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() proxysnapshot.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proxysnapshot.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: ctx
func (_m *MockSessionLimiter) Run(ctx context.Context) {
	_m.Called(ctx)
}

// NewMockSessionLimiter creates a new instance of MockSessionLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionLimiter {
	mock := &MockSessionLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
