# ubi makes it way easier to configure this.
FROM consul-dataplane/release-ubi:1.3.0-dev as consuldataplane

USER root

RUN microdnf install -y iptables sudo nc \
 	&& usermod -a -G wheel consul-dataplane \
 	&& echo 'consul-dataplane ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY --from=consul:local /bin/consul /bin/consul

COPY tproxy-startup.sh /bin/tproxy-startup.sh
RUN chmod +x /bin/tproxy-startup.sh && chown root:root /bin/tproxy-startup.sh

USER 100
