// Code generated by protoc-json-shim. DO NOT EDIT.
package meshv2beta1

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for ComputedGatewayConfiguration
func (this *ComputedGatewayConfiguration) MarshalJSON() ([]byte, error) {
	str, err := ComputedGatewayRoutesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedGatewayConfiguration
func (this *ComputedGatewayConfiguration) UnmarshalJSON(b []byte) error {
	return ComputedGatewayRoutesUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for ComputedGatewayListener
func (this *ComputedGatewayListener) MarshalJSON() ([]byte, error) {
	str, err := ComputedGatewayRoutesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedGatewayListener
func (this *ComputedGatewayListener) UnmarshalJSON(b []byte) error {
	return ComputedGatewayRoutesUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for ComputedHostnameRoutes
func (this *ComputedHostnameRoutes) MarshalJSON() ([]byte, error) {
	str, err := ComputedGatewayRoutesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedHostnameRoutes
func (this *ComputedHostnameRoutes) UnmarshalJSON(b []byte) error {
	return ComputedGatewayRoutesUnmarshaler.Unmarshal(b, this)
}

var (
	ComputedGatewayRoutesMarshaler   = &protojson.MarshalOptions{}
	ComputedGatewayRoutesUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
