// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbserver/v1alpha1/server.proto

package serverv1alpha1

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *ServerMetadata) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *ServerMetadata) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
