// Code generated by protoc-gen-resource-types. DO NOT EDIT.

package hcpv1alpha1

import (
	"github.com/hashicorp/consul/proto-public/pbresource"
)

const (
	GroupName = "hcp"
	Version   = "v1alpha1"

	CloudLinkKind = "CloudLink"
)

var (
	CloudLinkType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         CloudLinkKind,
	}
)
